### ISSUE TITLE
filter_query gt-date needs better documentation

### ISSUE THREAD

**Issue by frankiezz09** [storyblok/storyblok-js-client#7]
Hi everyone, I was trying to follow through the Storyblok documentation for Nuxt.js and I really find it hard to understand how we can use filter_query to get stories beyond a certain 'published_at' date. Here's my code snippet based on how I understand it from the documentation here (https://www.storyblok.com/docs/Delivery-Api/get-a-story)

```
return context.app.$storyapi 
.get('cdn/stories/', { 
	version: version, 
	filter_query: { 
		published_at: { 
			'gt-date': '2018-03-03 10:00', 
		}, 
	},
}).then(res => {
       ... rest of the code here
})
```

Using this snippet without the filter_query works fine, so I figured I may have been confused at some point on the usage of filter_query. Can anyone help me out on this or could refer me to a better documentation on my use case?

Edit: Sorry about the code format.

**Comment by DominikAngerer** [comment]
We'll introduce a rewrite of the documentation including an example area in the coming months! This will also allow examples added via github! I'm closing this for now - thanks for the feedback! If you have any questions or need help with a query feel free to meanwhile contact our live-chat directly :)

**Comment by nisansei** [comment]
I'm unfortunately also not able to get the date filtering to work for `published_at` or `first_published_at`. I see [the docs](https://www.storyblok.com/docs/api/content-delivery/v2/filter-queries/operation-lt-date) have been updated since this post was made, but the example is not working for these date fields.

Example query:
```
{
  filter_query: { published_at: { lt_date: '2024-09-01 11:11' } },
}
```

Neither `lt_date` nor `gt_date` works.

Surely this is supported somehow? If so, could you provide an example and perhaps include it in the docs?
